networks:
  default:
   driver: bridge
   name: roboshop
     #external: true if it is created manually 
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  mongodb:
   image: harshatejaadduri/mongodb:v1
   container_name: mongodb
   volumes:
     - mongodb:/data/db
  catalogue:
   image: harshatejaadduri/catalogue:v1
   container_name: catalogue
   depends_on: 
   - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
      - redis:/data
  user:
    image: harshatejaadduri/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: harshatejaadduri/cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: harshatejaadduri/mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
  shipping:
    image: harshatejaadduri/shipping:v1
    container_name: shipping
    depends_on:
      - cart
      - mysql
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq  
  payment:
    image: harshatejaadduri/payment:v1
    container_name: payment
    environment:
       CART_HOST: cart
       CART_PORT: 8080
       USER_HOST: user
       USER_PORT: 8080
       AMQP_HOST: rabbitmq
       AMQP_USER: roboshop
       AMQP_PASS: roboshop123
    depends_on:
      - cart
      - user
      - rabbitmq
  frontend:
    image: harshatejaadduri/frontend:v1
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
    - cart
    - catalogue
    - user
    - shipping
    - payment